/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-next')['BAlert']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdown: typeof import('bootstrap-vue-next')['BDropdown']
    BDropdownItem: typeof import('bootstrap-vue-next')['BDropdownItem']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarItem: typeof import('bootstrap-vue-next')['BNavbarItem']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BNavNav: typeof import('bootstrap-vue-next')['BNavNav']
    BProgress: typeof import('bootstrap-vue-next')['BProgress']
    Brand: typeof import('./src/components/Brand.vue')['default']
    Category: typeof import('./src/components/Category.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    HeaderApp: typeof import('./src/components/HeaderApp.vue')['default']
    LandingPage: typeof import('./src/components/LandingPage.vue')['default']
    Products: typeof import('./src/components/products.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
